root = "backend"
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
  cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "frontend", "dist"]
  delay = 500

[log]
  time = false

[server]
  port = 8790

[env]
  PORT = "8790"
